### PR TITLE
fix: added support of expressions in style and class names

### LINKED ISSUE #483: Style names don't support expressions
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added support of expressions in style and class names

## Issue ticket number and link

Closes #483 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/framework/src/hooks/useStyleNames.ts [hunk 1]
```diff
@@ -1,14 +1,60 @@
...
+): CSSProperties => {
+  let names: string[] = isString(styleNames)
+    ? styleNames.split(" ")
+    : styleNames;
+
+  names = names.map((styleName) => {
+    const isClass = styleName.startsWith(".");
+    const styleKey = isClass ? styleName.substring(1) : styleName;
+    const styleVal = isExpression(styleKey)
+      ? evaluate<string>(defaultScreenContext, styleKey, {
```
Comment (evshi) [inline packages/framework/src/hooks/useStyleNames.ts:28]: Don't use `evaluate` directly. Did you see the warning? Use `useEvaluate` and then update the dependency array of the second evaluation to include styles like we discussed.

**Review by evshi — CHANGES_REQUESTED** [review]

**Review by anserwaseem — APPROVED** [review]

File: packages/framework/src/hooks/useStyleNames.ts [hunk 2]
```diff
@@ -1,28 +1,56 @@
...
+  // evaluate classnames
+  const classStylesArray: string[] | undefined = isString(classStyles)
+    ? classStyles.split(" ")
+    : classStyles;
+  const styleClasses = useEvaluate({ classStylesArray });
+
+  const styleNames = [
+    ...(nameStyles.nameStylesArray
+      ? nameStyles.nameStylesArray.map((nameStyle) => `${nameStyle}`)
+      : []),
```
Comment (evshi) [inline packages/framework/src/hooks/useStyleNames.ts:47]: You don't need both the spread operator and map. Both will create new arrays.

File: packages/framework/src/hooks/useStyleNames.ts [hunk 3]
```diff
@@ -1,28 +1,56 @@
...
+  const nameStylesArray: string[] | undefined = isString(namedStyles)
+    ? namedStyles.split(" ")
+    : namedStyles;
+  const nameStyles = useEvaluate({ nameStylesArray });
+
+  // evaluate classnames
+  const classStylesArray: string[] | undefined = isString(classStyles)
+    ? classStyles.split(" ")
+    : classStyles;
+  const styleClasses = useEvaluate({ classStylesArray });
```
Comment (evshi) [inline packages/framework/src/hooks/useStyleNames.ts:42]: You can evaluate both in a single call - any reason to split them up here?

File: packages/framework/src/parser.ts [hunk 4]
```diff
@@ -348,9 +348,15 @@ const unwrapTheme = (theme?: string): EnsembleThemeModel | undefined => {
...
-  );
+  resolvedProps.forEach(([path, value]) => {
+    const stylePaths = path.split(".");
+    if (path.startsWith(".")) {
+      stylePaths.shift();
+      stylePaths[0] = `.${stylePaths[0]}`;
+    }
+
+    set(workingTheme.Styles!, [...stylePaths], value);
+  });
```
Comment (evshi) [inline packages/framework/src/parser.ts:359]: I still don't think I understand what this is doing. Can you add an example here? Or even better, a unit test?

File: packages/framework/src/hooks/useStyleNames.ts (hunk 3 above)
Comment (sagardspeed2) [reply packages/framework/src/hooks/useStyleNames.ts:42]: Yes, because on classStyle evaluation, we need to add prefix '.' that indicate that this one is class style

File: packages/framework/src/hooks/useStyleNames.ts (hunk 2 above)
Comment (sagardspeed2) [reply packages/framework/src/hooks/useStyleNames.ts:47]: this is for merge the names styles and class styles in single array

File: packages/framework/src/parser.ts (hunk 4 above)
Comment (sagardspeed2) [reply packages/framework/src/parser.ts:359]: this is very important for evaluate class styles with expressions
for example,

if theme file like,

```
{
    Styles: {
        .button-1: {
            backgroundColor: "${colors.primary['500']}"
        }
    }
}
```

and for evaluate this style correctly we need to convert them into
```
{
    Styles: {
        .button-1: {
            backgroundColor: "#ff0"
        }
    }
}
```

the logic here written is for set the value in object properties where key name starts with '.'

Comment (evshi) [reply packages/framework/src/parser.ts:359]: How is it a complex expression? What happens if the expression of the style is `${someValue ?? otherValue}`

**Comment by evshi** [comment]
Per discussion standup, let's add some unit tests for the parser changes to clarify what its purpose is.

File: apps/kitchen-sink/src/App.tsx [hunk 5]
```diff
@@ -1,7 +1,7 @@
 import type { ApplicationDTO } from "@ensembleui/react-framework";
 import { EnsembleApp } from "@ensembleui/react-runtime";
 // Screens
-import MenuYAML from "./ensemble/screens/menu.yaml";
+// import MenuYAML from "./ensemble/screens/menu.yaml";
```
Comment (evshi) [inline apps/kitchen-sink/src/App.tsx:4]: Please clean this up to original state

File: packages/framework/src/hooks/useEvaluate.ts [hunk 6]
```diff
@@ -21,7 +21,7 @@ export const useEvaluate = <T extends Record<string, unknown>>(
       findExpressions(values, [], expressionMap);
       return expressionMap;
     },
-    options?.refreshExpressions ? [values] : [],
+    options?.refreshExpressions ? [values] : [values?.styles],
```
Comment (evshi) [inline packages/framework/src/hooks/useEvaluate.ts:24]: Let's leave a comment here - `styles` should be an object that represents a set of style rules. I wonder if this is maybe something we can extend to be more generic and not be special to styles...

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 7]
```diff
@@ -40,12 +40,20 @@ export const useRegisterBindings = <T extends { [key: string]: unknown }>(
...
-  const styles = merge({}, styleProperties, values.styles);
-  if (!isEmpty(styles)) {
-    merge(values, { styles });
-  }
+  const styles = useMemo(() => {
+    return merge(
+      {},
+      styleProperties,
+      omit(values.styles ?? {}, ["className", "names"]),
+    );
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:48]: Instead of creating another hook here - let's combine this logic inside `useStyleNames` and rename the hook to `useStyles`

File: packages/framework/src/hooks/useStyleNames.ts [hunk 8]
```diff
@@ -1,28 +1,66 @@
...
+
+  const appliedStyles = {};
+  overlappingNames.forEach((name) => {
+    merge(appliedStyles, get(theme.Styles, name));
+  });
+
+  return appliedStyles;
+};
 
 export const useStyleNames = (
```
Comment (evshi) [inline packages/framework/src/hooks/useStyleNames.ts:26]: Rename to `useStyleSet` or something that better describes what this does.

File: packages/framework/src/hooks/useStyleNames.ts [hunk 9]
```diff
@@ -1,28 +1,66 @@
...
+      namedStyles.split(/([a-zA-Z0-9_-]+)\s+(\${.+?})\s+(\w+)/).filter((x) => x)
+    : namedStyles;
 
-  if (styleNames && themeContext) {
-    return resolveStyleNames(styleNames, themeContext);
-  }
+  // evaluate classnames
+  const classStylesArray: string[] | undefined = isString(classStyles)
+    ? // eslint-disable-next-line prefer-named-capture-group
+      classStyles.split(/([a-zA-Z0-9_-]+)\s+(\${.+?})\s+(\w+)/)
```
Comment (evshi) [inline packages/framework/src/hooks/useStyleNames.ts:41]: Can we reuse the same regex everywhere, i.e. from fetcher.ts?

File: packages/framework/src/hooks/useStyleNames.ts [hunk 10]
```diff
@@ -1,28 +1,66 @@
...
+    nameStylesArray: namedStylesArrayEval,
+  } = useEvaluate({
+    classStylesArray,
+    nameStylesArray,
+  });
+
+  const styleNames = [
+    ...(namedStylesArrayEval
+      ?.filter((className) => className)
+      .map((nameStyle) => `${nameStyle}`) || []),
```
Comment (evshi) [inline packages/framework/src/hooks/useStyleNames.ts:55]: You can just use lodash.compact to remove nulls/undefined. It will also create a new array.

**Review by evshi — COMMENTED** [review]
Glad we got this to the right solution. Let's clean up the code

File: packages/framework/src/hooks/useStyleNames.ts (hunk 9 above)
Comment (sagardspeed2) [reply packages/framework/src/hooks/useStyleNames.ts:41]: No, because this regex is for split string, so we can convert string into array of classname or stylename, and that classname or stylename, may be expression or not.

and the regex added in fetcher is for checking that given string is expression or not.

File: packages/framework/src/hooks/useEvaluate.ts (hunk 6 above)
Comment (evshi) [reply packages/framework/src/hooks/useEvaluate.ts:24]: @sagardspeed2 please leave a comment here

File: packages/framework/src/hooks/useStyles.ts [hunk 11]
```diff
@@ -0,0 +1,81 @@
...
+    nameStylesArray: namedStylesArrayEval,
+  } = useEvaluate({
+    classStylesArray,
+    nameStylesArray,
+  });
+
+  const styleNames = compact([
+    ...namedStylesArrayEval.map((nameStyle) => `${nameStyle}`),
+    ...classStylesArrayEval.map((className) => `.${className}`),
+  ]).join(" ");
```
Comment (evshi) [inline packages/framework/src/hooks/useStyles.ts:66]: This can be moved inside the next useMemo and there's no point joining and resplitting.

File: packages/framework/src/hooks/useStyles.ts [hunk 12]
```diff
@@ -0,0 +1,81 @@
...
+  const {
+    classStylesArray: classStylesArrayEval,
+    nameStylesArray: namedStylesArrayEval,
+  } = useEvaluate({
+    classStylesArray,
+    nameStylesArray,
+  });
+
+  const styleNames = compact([
+    ...namedStylesArrayEval.map((nameStyle) => `${nameStyle}`),
```
Comment (evshi) [inline packages/framework/src/hooks/useStyles.ts:64]: This map is not required.

File: packages/framework/src/hooks/useStyles.ts [hunk 13]
```diff
@@ -0,0 +1,81 @@
...
+
+  const { classStylesArray, nameStylesArray } = useMemo(() => {
+    const stringSplitter = (styles: string): string[] =>
+      // eslint-disable-next-line prefer-named-capture-group
+      styles.split(/([a-zA-Z0-9_-]+)\s+(\${.+?})\s+(\w+)/).filter(Boolean);
+    return {
+      classStylesArray: isString(classStyles)
+        ? stringSplitter(classStyles)
+        : [],
+      nameStylesArray: isString(namedStyles) ? stringSplitter(namedStyles) : [],
```
Comment (evshi) [inline packages/framework/src/hooks/useStyles.ts:51]: Does this still work if there are mixed static and expressions, for example

```yaml
styles:
  className: "myStyle ${ensemble.storage.get('myOtherStyle')}"
```

I think a better way to do this is to just treat the entire thing as a string interpolation.

**Review by evshi — CHANGES_REQUESTED** [review]
@sagardspeed2 there is still lots to clean up.

File: packages/framework/src/hooks/useStyles.ts (hunk 13 above)
Comment (sagardspeed2) [reply packages/framework/src/hooks/useStyles.ts:51]: Yes, and we just can't treat this as entire string interpolation, as due to classname we need to add '.' as prefix on each classname

File: packages/framework/src/hooks/useStyles.ts (hunk 11 above)
Comment (sagardspeed2) [reply packages/framework/src/hooks/useStyles.ts:66]: No that is wrong, we need to place this outside of useMemo and convert it into string and later resplitting. otherwise this will go into infinite render due to array gives new reference each time.

File: packages/framework/src/hooks/useStyles.ts [hunk 14]
```diff
@@ -35,40 +34,28 @@ const resolveStyleNames = (
...
+      namedStyles: `\${\`${namedStyles || ""}\`}`,
+    });
 
   const styleNames = compact([
-    ...namedStylesArrayEval,
-    ...classStylesArrayEval.map((className) => `.${className}`),
+    ...(classStylesEval.trim()
+      ? classStylesEval.split(" ").map((className) => `.${className}`)
+      : []),
+    ...[namedStylesEval.trim()],
```
Comment (evshi) [inline packages/framework/src/hooks/useStyles.ts:52]: Don't need to split here?

Comment (sagardspeed2) [reply packages/framework/src/hooks/useStyles.ts:52]: We need to assign `.` prefix  to each classname, and this is the only reason to split here

**Review by evshi — APPROVED** [review]
