### PR TITLE
fix: added inputNumber for input type number

### LINKED ISSUE #782: Error when `inputType: number` is used with `maxLength` in `TextInput`
**Describe the bug**
Getting this error when `inputType: number` is used with `maxLength` in `TextInput`

```
React Router caught the following error during render DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
```

You will get the error when you type more words than the limit
e.g if limit is 5 try to write 6 words

Try here: https://studio.ensembleui.com/app/yeveBgUUti3DDVe8X3DE/screen/ngXZxiPDSV7nvlR9ZOD9

**Screenshots**
image

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added inputNumber for input type number

## Issue ticket number and link

Closes #782 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

### CODE REVIEW

**Review by evshi — CHANGES_REQUESTED** [review]
@sagardspeed2 this doesn't meet the requirements at all. I am able to type way more digits than should be allowed. `InputNumber` also has completely different styling.

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 1]
```diff
@@ -58,6 +58,30 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
     [action],
   );
 
+  const handleKeyDown = useCallback(
+    (e: React.KeyboardEvent<HTMLInputElement>) => {
+      if (values?.inputType !== "number") {
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:63]: Let's only attach the handler if the inputType is number.

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 2]
```diff
@@ -58,6 +58,30 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
...
+      const isNumericKey = /^\d$/.test(e.key); // Numpad keys (96-105)
+      const isControlKey = [
+        "Backspace",
+        "Tab",
+        "ArrowLeft",
+        "ArrowRight",
+      ].includes(e.key);
+      const isCopyPasteCut =
+        (e.ctrlKey || e.metaKey) &&
+        ["c", "v", "x"].includes(e.key.toLowerCase());
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:76]: I think just check if the meta/ctrl key is pressed and let the default behavior go through if so.

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 3]
```diff
@@ -58,6 +58,28 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
...
+      }
+
+      const isNumericKey = /^\d$/.test(e.key); // Numpad keys (96-105)
+      const isControlKey = [
+        "Backspace",
+        "Tab",
+        "ArrowLeft",
+        "ArrowRight",
+      ].includes(e.key);
+      const isCopyPasteCut = e.ctrlKey || e.metaKey;
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:74]: This may be a better solution than checking for keys individually https://stackoverflow.com/a/70401792

**Comment by evshi** [comment]
Also can you please add some tests for this?

**Comment by evshi** [comment]
@sagardspeed2 can you please add some unit tests for this

**Comment by sagardspeed2** [comment]
> @sagardspeed2 can you please add some unit tests for this

I am writing a unit tests for this

File: packages/runtime/src/widgets/Form/__tests__/TextInput.test.tsx [hunk 4]
```diff
@@ -0,0 +1,137 @@
+/* eslint-disable react/no-children-prop */
+import { fireEvent, render, screen, waitFor } from "@testing-library/react";
+import type { PropsWithChildren } from "react";
+import { BrowserRouter } from "react-router-dom";
+import { ScreenContextProvider } from "@ensembleui/react-framework";
+import { Button, Form } from "../../index";
+
+// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
+global.ResizeObserver = require("resize-observer-polyfill");
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/__tests__/TextInput.test.tsx:9]: This isn't needed anymore I did it once in setuptests.js

**Review by evshi — APPROVED** [review]
