### PR TITLE
center align button's icon when no label is given

### LINKED ISSUE #770: Button with just an icon not center aligned
**Describe the bug**
https://discord.com/channels/1031982848485359626/1268910343824867359

**Expected behavior**
when a Button with either `startingIcon` or `endingIcon` is use without label, icon should be center aligned.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by anserwaseem**
## Describe your changes
before:
image

after:
image

## Issue ticket number and link

Closes #770 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/Button.tsx [hunk 1]
```diff
@@ -82,7 +82,6 @@ export const Button: React.FC<ButtonProps> = ({ id, onTap, ...rest }) => {
         {!loading && values?.startingIcon ? (
           <Icon {...values.startingIcon} />
         ) : null}
-        {!loading && values?.startingIcon ? <>&nbsp;</> : null}
```
Comment (evshi) [inline packages/runtime/src/widgets/Button.tsx:85]: This white space should be included in the element above.

**Review by evshi — APPROVED** [review]
