### PR TITLE
fix: added support for onResponse and onError in ensemble.invokeAPI

### LINKED ISSUE #860: API onResponse and onError do not execute when invoking API via code
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
added support for onResponse and onError in ensemble.invokeAPI

## Issue ticket number and link

Closes #860 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/framework/src/shared/models.ts [hunk 1]
```diff
@@ -72,8 +72,8 @@ export interface EnsembleAPIModel {
   headers?: { [key: string]: string | number | boolean };
   cacheExpirySeconds?: number;
   body?: string | object;
-  onResponse?: EnsembleAction;
-  onError?: EnsembleAction;
+  onResponse?: EnsembleAction | EnsembleActionHookResult;
+  onError?: EnsembleAction | EnsembleActionHookResult;
```
Comment (evshi) [inline packages/framework/src/shared/models.ts:76]: Store as separate property

File: packages/runtime/src/runtime/screen.tsx [hunk 2]
```diff
@@ -34,6 +35,7 @@ export const EnsembleScreen: React.FC<EnsembleScreenProps> = ({
   const routeParams = useParams(); // route params
   const params = new URLSearchParams(search); // query params
   const queryParams: { [key: string]: unknown } = Object.fromEntries(params);
+  const [apis, setApis] = useState<EnsembleAPIModel[]>([]);
```
Comment (evshi) [inline packages/runtime/src/runtime/screen.tsx:38]: Use a map for easy lookup.

File: packages/runtime/src/runtime/screen.tsx [hunk 3]
```diff
@@ -91,34 +93,76 @@ export const EnsembleScreen: React.FC<EnsembleScreenProps> = ({
...
+  api,
+  currentIndex,
+  setApis,
+}: {
+  api: EnsembleAPIModel;
+  currentIndex: number;
+  setApis: React.Dispatch<React.SetStateAction<EnsembleAPIModel[]>>;
+}): null => {
+  const onResponse = useEnsembleAction(api.onResponse as EnsembleAction);
+  const onError = useEnsembleAction(api.onError as EnsembleAction);
```
Comment (evshi) [inline packages/runtime/src/runtime/screen.tsx:154]: This needs to happen inside the ScreenProvider/ModalWrapper.

Comment (sagardspeed2) [reply packages/runtime/src/runtime/screen.tsx:154]: I think this is the best place to convert that into callback, because we need to this in runtime only. other thing is to after converting them into callback, we need to store them in screenAtom, thus we can consume that into framework by accessing from screenAtom by screenContext.

File: packages/runtime/src/runtime/screen.tsx (hunk 2 above)
Comment (sagardspeed2) [reply packages/runtime/src/runtime/screen.tsx:38]: @evshi sorry, but I did not understand your suggestion about use of map

File: packages/runtime/src/runtime/screen.tsx (hunk 3 above)
Comment (evshi) [reply packages/runtime/src/runtime/screen.tsx:154]: I don't think you are understanding me here. This evaluation needs to happen inside of the screen and modal context otherwise the other actions won't work

File: packages/runtime/src/runtime/screen.tsx (hunk 2 above)
Comment (evshi) [reply packages/runtime/src/runtime/screen.tsx:38]: Instead of an array of API models, use a map.

File: packages/runtime/src/runtime/screen/wrapper.tsx [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+  children,
+}) => {
+  const { apis = [], setApi } = useScreenData();
+
+  return (
+    <>
+      {apis.map((api, index) => (
+        <EvaluateApi
+          api={api}
+          currentIndex={index}
```
Comment (evshi) [inline packages/runtime/src/runtime/screen/wrapper.tsx:16]: You don't need index. Each API in the screen is uniquely identified by its name.

File: packages/runtime/src/runtime/screen/index.tsx [hunk 5]
```diff
@@ -102,18 +103,20 @@ export const EnsembleScreen: React.FC<EnsembleScreenProps> = ({
...
+          </OnLoadAction>
+          {screen.menu ? (
+            <EnsembleMenu
+              menu={{ ...screen.menu }}
+              renderOutlet={false}
+              type={screen.menu.type}
+            />
+          ) : null}
+          <EnsembleFooter footer={screen.footer} />
+        </ScreenApiWrapper>
```
Comment (evshi) [inline packages/runtime/src/runtime/screen/index.tsx:119]: This doesn't need to wrap the children elements it can be a sibling.

**Review by evshi — APPROVED** [review]
