### PR TITLE
fix: added stickey header and footer in data grid

### LINKED ISSUE #364: Enable sticky header and footer in DataGrid

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added feature for enable stickey header and footer in data grid widget

## Issue ticket number and link

Closes #
closes #364 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx [hunk 1]
```diff
@@ -168,14 +171,16 @@ export const DataGrid: React.FC<GridProps> = (props) => {
               }
             : undefined
         }
+        scroll={
+          values?.scrollable ? { y: values.scrollHeight || 150 } : undefined
+        }
```
Comment (evshi) [inline packages/runtime/src/widgets/DataGrid/DataGrid.tsx:176]: Having two properties seems redundant here. Let's just expose the scroll config object

File: apps/kitchen-sink/src/ensemble/screens/widgets.yaml [hunk 2]
```diff
@@ -49,11 +49,203 @@ View:
...
                     - label: ICON
                     - label: MENU
+                  scroll:
+                    scrollHeight: 400
                   item-template:
                     data:
                       [
                         { key: "1", patient: "John", advocate: "Mike Ross" },
-                        { key: "2", patient: "Reuben", advocate: "Harvey Dent" },
+                        {
```
Comment (evshi) [inline apps/kitchen-sink/src/ensemble/screens/widgets.yaml:58]: Bind to endpoint instead of static data

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx [hunk 3]
```diff
@@ -55,17 +55,24 @@ export interface DataGridRowTemplate {
...
 
+export interface DataGridScrollable {
+  scrollHeight: string;
+}
+
 export type GridProps = {
   allowSelection?: boolean;
   onRowsSelected?: EnsembleAction;
   DataColumns: DataColumn[];
+  scrollable?: boolean;
```
Comment (evshi) [inline packages/runtime/src/widgets/DataGrid/DataGrid.tsx:66]: Remove unused properties

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx [hunk 4]
```diff
@@ -55,17 +55,24 @@ export interface DataGridRowTemplate {
   };
 }
 
+export interface DataGridScrollable {
+  scrollHeight: string;
```
Comment (evshi) [inline packages/runtime/src/widgets/DataGrid/DataGrid.tsx:59]: Let's add width while you're at it

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx [hunk 5]
```diff
@@ -142,6 +149,7 @@ export const DataGrid: React.FC<GridProps> = (props) => {
         onRow={(record, recordIndex) => {
           return { onClick: () => onTapActionCallback(record, recordIndex) };
         }}
+        pagination={values?.hidePagination ? false : undefined}
```
Comment (evshi) [inline packages/runtime/src/widgets/DataGrid/DataGrid.tsx:152]: `values.hidePagination !== true`

Comment (sagardspeed2) [reply packages/runtime/src/widgets/DataGrid/DataGrid.tsx:152]: We can't update this condition that return the bool, as pagination only accept either false or undefined.

**Review by evshi — APPROVED** [review]
