### PR TITLE
fix: search in multiselect

### LINKED ISSUE #555: Multiselect search not working
**Describe the bug**

Image

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
fix search issue in multiselect

## Issue ticket number and link

Closes #555 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/Form/MultiSelect.tsx [hunk 1]
```diff
@@ -264,6 +268,7 @@ const MultiSelect: React.FC<MultiSelectProps> = (props) => {
             notFoundContent="No Results"
             onChange={handleChange}
             onSearch={handleSearch}
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/MultiSelect.tsx:270]: Why do we need both handleSearch and filter options?

Comment (sagardspeed2) [reply packages/runtime/src/widgets/Form/MultiSelect.tsx:270]: image

As per the previous implementation inside the Multiselect widget, when there is no matching option found and user allow to create custom option, we want to show something like this in UI, that's why we need handleSearch

Comment (evshi) [reply packages/runtime/src/widgets/Form/MultiSelect.tsx:270]: Can we leave a comment about this?

**Review by evshi — APPROVED** [review]
