### PR TITLE
fix: mask input required validation

### LINKED ISSUE #857: Using mask property on text input makes the field required
**Describe the bug**
If you use a mask but set required false, the input will still error with an empty value.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
fix mask input required validation

## Issue ticket number and link

Closes #857 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

**Review by anserwaseem — APPROVED** [review]

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 1]
```diff
@@ -198,7 +198,7 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
     if (values?.mask && patternValue) {
       rulesArray.push({
         validator: (_, inputValue?: string) => {
-          if (new RegExp(patternValue).test(inputValue || "")) {
+          if (new RegExp(patternValue).test(inputValue || "") || !inputValue) {
```
Comment (anserwaseem) [inline packages/runtime/src/widgets/Form/TextInput.tsx:201]:
```suggestion
          if (!inputValue || new RegExp(patternValue).test(inputValue)) {
```

**Review by anserwaseem — CHANGES_REQUESTED** [review]
also add `values?.validator?.maskError` in the dependency array of rules memo

**Review by anserwaseem — APPROVED** [review]
