### PR TITLE
fix: column headers

### LINKED ISSUE #1025: Empty table columns have headers that break words
**Describe the bug**

Image

If a column is empty, the header shrinks and breaks up the title.

**To Reproduce**

**Expected behavior**
Title should be legible

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
fix: column headers to not shrink

## Issue ticket number and link

Closes #1025 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

### CODE REVIEW

**Review by justEhmadSaeed — APPROVED** [review]
lgtm
image
image

File: packages/runtime/src/widgets/Form/MultiSelect.tsx [hunk 1]
```diff
@@ -207,10 +207,10 @@ const MultiSelect: React.FC<MultiSelectProps> = (props) => {
   // handle option change
   const handleChange = (
     value: MultiSelectOption[],
-    option: MultiSelectOption | MultiSelectOption[],
+    option?: MultiSelectOption | MultiSelectOption[],
   ): void => {
     setSelectedValues(value);
-    if (action) onChangeCallback({ value, option });
+    if (action) onChangeCallback({ value, option: option ?? [] });
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/MultiSelect.tsx:213]: Is this intended?

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx [hunk 2]
```diff
@@ -514,6 +515,7 @@ export const DataGrid: React.FC<GridProps> = (props) => {
                 }))}
                 hidden={col.visible === false}
                 key={colIndex}
+                minWidth={col.width ?? 100}
```
Comment (evshi) [inline packages/runtime/src/widgets/DataGrid/DataGrid.tsx:518]: Are these both needed?

File: packages/runtime/src/widgets/Form/MultiSelect.tsx (hunk 1 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/Form/MultiSelect.tsx:213]: Yes

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx (hunk 2 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/DataGrid/DataGrid.tsx:518]: Yes
