### PR TITLE
fix: added support for mask textInput

### LINKED ISSUE #835: Mask not working for TextInput widgets
**Describe the bug**
`mask` property is not working for `TextInput` widgets

**To Reproduce**
1. Create a `TextInput` widget
2. Add property `mask: "###-###-####"`
3. Input is not properly formatted according to the mask

**Additional context**
https://github.com/atlas-health/atlas-navigator-ui/pull/1196#issuecomment-2361334136
[Kitchen sink example](https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/abc081b1-bcb4-4db6-ae55-7987cb6c418e)

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added mask format support in textInput

### Screenshots [Optional]

https://github.com/user-attachments/assets/554a817e-d505-40a1-b5e1-9e464afa821c

## Issue ticket number and link

Closes #835 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

### CODE REVIEW

**Review by evshi — COMMENTED** [review]
AFAIK this works already? What exactly is this fixing?

cc: @anserwaseem

**Comment by sagardspeed2** [comment]
@evshi @anserwaseem 
Previously mask was only working on validation time and it was not formatting the entered text into given mask format. In this PR, when user enter the text, it automatically formated with given mask pattern

**Comment by anserwaseem** [comment]
@sagardspeed2 please fix this issue as well

https://github.com/user-attachments/assets/bc056358-98bf-43a2-a644-95ffbc48f5f4

```yaml
- TextInput:
      label: phone 1
      hintText: +1-123-456-7890
      mask: "+1-###-###-####"
      required: true
  - TextInput:
      label: phone 1
      hintText: +1-123-456-7890
      mask: "+1-###-###-####"
      inputType: phone
```

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 1]
```diff
@@ -81,6 +91,15 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
...
   }, [value, formInstance, values?.id, values?.label]);
 
+  useEffect(() => {
+    if (values?.mask && maskRef.current) {
+      IMask(maskRef.current.input, {
+        mask: values.mask.replace(/#/g, "0").replace(/A/g, "a"),
+        lazy: true,
+      });
+    }
+  }, [values, value, handleChange]);
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:101]: Fix this dependency array - remove unused dependencies and be more specific, e.g. values.mask instead of values.

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 2]
```diff
@@ -236,7 +255,11 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
               onInput: (event): void => handleKeyDown(event),
             })}
             placeholder={values?.hintText ?? ""}
-            ref={rootRef}
+            ref={(myRef: null): null => {
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:258]: This type is incorrect.

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 3]
```diff
@@ -43,6 +51,8 @@ export type TextInputProps = {
 
 export const TextInput: React.FC<TextInputProps> = (props) => {
   const [value, setValue] = useState<string>();
+  const maskRef = useRef<MaskInputRef | null>(null);
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:54]: Can we not just use `HTMLInputElement` here or something?

**Comment by evshi** [comment]
@anserwaseem had a discussion with @sagardspeed2 on the duplicate issue - it's up to the user to ensure their text fields have unique id/label combination within the form scope.

**Comment by anserwaseem** [comment]
@sagardspeed2 can we please have `maskError` property on TextInput?
CC: @evshi

**Review by evshi — APPROVED** [review]
