### PR TITLE
fix: support expression evaluate inside placeholder of search widget

### LINKED ISSUE #288: Search bar properties are not all expressions
**Describe the bug**
Search bar does not use expressions for all of its properties

**To Reproduce**

1. Go to screen with Search
2. Try using expression in placeholder
3. Text is just the expression

**Expected behavior**
Expression should be evaluated

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Support expression evaluation inside placeholder string of search widgets

## Issue ticket number and link

Closes #
closes #288

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests

### CODE REVIEW

File: packages/runtime/src/widgets/Search.tsx [hunk 1]
```diff
@@ -54,7 +54,7 @@ export const Search: React.FC<SearchProps> = ({
     name: itemTemplate?.name,
   });
   const { rootRef, values } = useRegisterBindings(
-    { styles, value, options },
+    { styles, value, options, placeholder },
```
Comment (evshi) [inline packages/runtime/src/widgets/Search.tsx:57]: Let's destructure the props for the props that shouldn't be expressions but then otherwise pass everything in as bindings, so be inclusive instead of exclusive. There's a few examples of this like `Column`. This avoids us having to update it further for every new property.

**Review by evshi — APPROVED** [review]
