### PR TITLE
fix: mask property not working

### LINKED ISSUE #878: TextInput: mask property not working if user copy pastes unmasked number
Ref: https://atlashealth.atlassian.net/browse/TRINITY-922

Try here: https://studio.ensembleui.com/app/yeveBgUUti3DDVe8X3DE/screen/z9VD6YRNWqQ55GDL7ekv

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
fix paste data on mask pattern update value

## Issue ticket number and link

Closes #878 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/Form/TextInput.tsx [hunk 1]
```diff
@@ -80,6 +81,17 @@ export const TextInput: React.FC<TextInputProps> = (props) => {
     target.value = target.value.replace(/[^0-9.]/g, "");
   }, []);
 
+  const handleInputPaste = useCallback(
+    (e: React.ClipboardEvent) => {
+      const pastedData = e.clipboardData.getData("Text");
```
Comment (evshi) [inline packages/runtime/src/widgets/Form/TextInput.tsx:86]: This should be lower case `text`? According to the standard https://html.spec.whatwg.org/multipage/dnd.html#dom-datatransfer-getdata

**Review by evshi — APPROVED** [review]
