### PR TITLE
add useThemeContext hook to fix style names not being applied

### LINKED ISSUE #246: Style names properties are not injected properly
**Describe the bug**
Style names are added to the component, but the properties are not applied to the widget.

**To Reproduce**

1. Go to app theme
2. Add a Styles block
3. Add a style name to the block with some styles
4. Add style name to a widget in yaml
5. See that the style name is added to class names but styles are not applied.

**Expected behavior**
Style properties are applied to widget

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by anserwaseem**
## Issue ticket number and link

Closes #246

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests

### CODE REVIEW

File: packages/framework/src/hooks/useThemeContext.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+import { useAtomValue } from "jotai";
+import type { CSSProperties } from "react";
+import { resolveStyleNames } from "../shared";
+import { themeAtom } from "../state";
+
+export const useThemeContext = (
```
Comment (evshi) [inline packages/framework/src/hooks/useThemeContext.ts:6]: Rename to `useStyleNames`

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 2]
```diff
@@ -23,6 +24,9 @@ export const useRegisterBindings = <T extends Record<string, unknown>>(
 ): RegisterBindingsResult<T> => {
   const { resolvedWidgetId, rootRef } = useWidgetId(id);
   const [widgetState, setWidgetState] = useWidgetState<T>(resolvedWidgetId);
+  const themeContext = useThemeContext(
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:27]: The properties can also contain expressions so these need to be merged with the style properties before the expression evaluation

File: packages/framework/src/hooks/useThemeContext.ts [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  styleNames?: string | string[],
```
Comment (evshi) [inline packages/framework/src/hooks/useThemeContext.ts:7]: This should be Expression<string | string[]>

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 4]
```diff
@@ -23,6 +24,9 @@ export const useRegisterBindings = <T extends Record<string, unknown>>(
...
+    (values?.styles as Record<string, unknown>)?.names as string | string[],
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:28]: You shouldn't need so much type casting...this is a sign the pieces are not fitting together right. It's the whole purpose of typing.

**Review by evshi — CHANGES_REQUESTED** [review]

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 5]
```diff
@@ -5,25 +5,44 @@ import isEqual from "react-fast-compare";
...
+import { useStyleNames } from "./useStyleNames";
 
 export interface RegisterBindingsResult<T> {
   id: string;
   values?: T;
   rootRef: RefCallback<never>;
 }
 
-export const useRegisterBindings = <T extends Record<string, unknown>>(
+interface Bindings {
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:20]: What's the purpose of adding this type?

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 6]
```diff
@@ -23,7 +24,16 @@ export const useRegisterBindings = <T extends Record<string, unknown>>(
...
+  const themeContext = useStyleNames(String(get(values, ["styles", "names"])));
 
+  const styles = merge({}, themeContext, values?.styles);
+  merge(
+    values,
+    !isEmpty(styles) && {
+      ...values,
+      styles,
+    },
+  );
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:36]: Just merge once? The function is recursive. There's no point shallow copying the values since merge will keep the original value if the key is undefined. https://lodash.com/docs/4.17.15#merge

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 7]
```diff
@@ -23,6 +24,16 @@ export const useRegisterBindings = <T extends Record<string, unknown>>(
 ): RegisterBindingsResult<T> => {
   const { resolvedWidgetId, rootRef } = useWidgetId(id);
   const [widgetState, setWidgetState] = useWidgetState<T>(resolvedWidgetId);
+  const themeContext = useStyleNames(
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:27]: nit: rename to styleProperties

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 8]
```diff
@@ -23,6 +24,16 @@ export const useRegisterBindings = <T extends Record<string, unknown>>(
...
+    isString(get(values, ["styles", "names"]))
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:28]: nit: store in a variable instead of calling get twice

**Review by evshi — APPROVED** [review]

**Review by evshi — APPROVED** [review]
