### PR TITLE
fix: tabBar stretch options

### LINKED ISSUE #593: TabBar: do not stretch?
ref: https://discord.com/channels/1031982848485359626/1241189980404056157

`tabPosition: start` & `tabNavBorderRadius` aren't working

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added support to choose tabBar stretch option

### Screenshots [Optional]
image

image

## Issue ticket number and link

Closes #593 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have added tests
- [ ] I have added a changeset `pnpm changeset add`
- [ ] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/TabBar.tsx [hunk 1]
```diff
@@ -28,12 +29,13 @@ export interface TabStyles {
...
   tabNavBottomBorderShow: boolean;
   tabColor: string;
+  tabNavStretch: boolean;
 }
 
 export interface TabBarStyles extends EnsembleWidgetStyles {
   inkBarShow: boolean;
   activeTabBackgroundColor: string;
-  tabPosition: "start" | "stretch";
+  tabPosition: TabsPosition;
```
Comment (evshi) [inline packages/runtime/src/widgets/TabBar.tsx:38]: Support the ensemble abstraction, don't expose the implementation type.

File: packages/runtime/src/widgets/TabBar.tsx [hunk 2]
```diff
@@ -28,12 +29,13 @@ export interface TabStyles {
   tabNavBorderRadius: string;
   tabNavBottomBorderShow: boolean;
   tabColor: string;
+  tabNavStretch: boolean;
```
Comment (evshi) [inline packages/runtime/src/widgets/TabBar.tsx:32]: This is not needed it's covered by tabPosition.

**Review by evshi — CHANGES_REQUESTED** [review]

**Review by evshi — APPROVED** [review]
