### PR TITLE
fix: added context in item-template

### LINKED ISSUE #885: No Context in item-template of Collapsible widget
**Describe the bug**
Use `item-template` in Collapsible widget. Example YAML
```yaml
Collapsible:
  item-template:
    data: [1, 2, 3]
    name: p
    template:
      CollapsibleItem:
        key: ${p}
        label: ${'hello' + getDateLabel(p)}
        children:
          Text:
            text: ${'world' + p + ensemble.storage.get("iconName")}
```

**Errors**
image
image
fyi: getDateLabel is available in common.js script in kitchen-sink app

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added context in item-template of collapsible widget

### Screenshots [Optional]
After

image

## Issue ticket number and link

Closes #885 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 1]
```diff
@@ -72,6 +85,10 @@ export type CollapsibleProps = {
   HasItemTemplate;
 
 export const Collapsible: React.FC<CollapsibleProps> = (props) => {
+  const screenContext = useScreenContext();
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:88]: Do not use screen context directly. Does the deprecated warning not show up for you?

**Review by evshi — CHANGES_REQUESTED** [review]

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 1 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/Collapsible.tsx:88]: it did, but without this, not able to evaluate the value. I take reference from the chart widget for this

Comment (evshi) [reply packages/runtime/src/widgets/Collapsible.tsx:88]: Use the useEvaluate hook for this.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 2]
```diff
@@ -106,49 +119,21 @@ export const Collapsible: React.FC<CollapsibleProps> = (props) => {
...
-            // eslint-disable-next-line prefer-named-capture-group
-            .replace(/['"]\$\{([^}]*)\}['"]/g, "$1"), // replace "${...}" or '${...}' with ...
-          {
-            [itemTemplate.name]: get(item, itemTemplate.name) as unknown,
-          },
-        );
-
         return {
           ...item,
-          key: evaluatedConfig.key,
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:127]: Where did the key go? This is important for opening programmatically.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 3]
```diff
@@ -71,6 +70,20 @@ export type CollapsibleProps = {
...
 
+const CollapsibleContentRenderer = ({ content }: { content: unknown }) => {
+  const { evaluatedContent } = useEvaluate({ evaluatedContent: content });
+
+  return (
+    <>
+      {isString(content)
+        ? evaluatedContent
+        : EnsembleRuntime.render([
+            unwrapWidget(content as { [key: string]: unknown }),
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:81]: This needs to be memoized it can't be called multiple times.

**Review by evshi — CHANGES_REQUESTED** [review]
Please write a test suite to avoid regressions

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 4]
```diff
@@ -71,9 +76,76 @@ export type CollapsibleProps = {
...
+  const evaluatedItem = useMemo(() => {
+    const { key, label, children } = evaluated as {
+      [key: string]: Expression<string>;
+    };
+
+    const header = isString(label)
+      ? label
+      : EnsembleRuntime.render([unwrapWidget(label)]);
+
+    const content = isString(children)
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:100]: The content can not be a string.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 5]
```diff
@@ -71,9 +76,76 @@ export type CollapsibleProps = {
...
+      ? children
+      : EnsembleRuntime.render([unwrapWidget(children)]);
+
+    return {
+      key,
+      label: header as Expression<string>,
+      children: content as Expression<string>,
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:107]: These should be ReactNodes.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 6]
```diff
@@ -71,9 +76,76 @@ export type CollapsibleProps = {
 } & EnsembleWidgetProps &
   HasItemTemplate;
 
+const Panel = ({
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:79]: Rename this.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 7]
```diff
@@ -71,9 +76,76 @@ export type CollapsibleProps = {
...
+  scope,
+  setTemplateItems,
+  template,
+}: {
+  scope: CustomScope;
+  template: CollapsibleItem;
+  setTemplateItems: React.Dispatch<React.SetStateAction<CollapsibleItem[]>>;
+}): null => {
+  const evaluated = useEvaluate({ ...template }, { context: scope });
+  const itemAddedRef = useRef(0);
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:89]: Why do you need this?

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 8]
```diff
@@ -71,9 +76,76 @@ export type CollapsibleProps = {
...
+
+  const evaluatedItem = useMemo(() => {
+    const { key, label, children } = evaluated as {
+      [key: string]: Expression<string>;
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:93]: This cast shouldn't be needed. The object type is inferred based on what you pass in.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 9]
```diff
@@ -71,9 +76,76 @@ export type CollapsibleProps = {
...
+      label: header as Expression<string>,
+      children: content as Expression<string>,
+    };
+  }, [evaluated]) as CollapsibleItem;
+
+  useEffect(() => {
+    itemAddedRef.current += 1;
+    if (itemAddedRef.current === 2) {
+      setTemplateItems((prev) => [...prev, { ...evaluatedItem }]);
+    }
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:115]: If `itemAddedRef` is being used to track render count, do not do that. Update this hook to check if the item has been previously added based on the key.

File: apps/kitchen-sink/src/ensemble/screens/home.yaml [hunk 10]
```diff
@@ -370,6 +371,19 @@ View:
                     executeCode: |
                       console.log('>>>', {tooltipState})
 
+        - Collapsible:
+            value: [2]
+            item-template:
+              data: [1, 2, 3]
+              name: p
+              template:
+                CollapsibleItem:
```
[the remark this answers is not in the document]
Comment (sagardspeed2) [reply apps/kitchen-sink/src/ensemble/screens/home.yaml:380]: We are supporting Collapsible and Accordion as Collapsible widget in react to give backward compatibility for atlas

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 4 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/Collapsible.tsx:100]: what if the user passed the string as children of collapsible item ?
For ex.

```yaml
Collapsible:
  value: [2]
  item-template:
    data: [1, 2, 3]
    name: p
    template:
      CollapsibleItem:
        key: ${p}
        label: ${'hello' + getDateLabel(p)}
        children: hiii there ${p}
```

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 5 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/Collapsible.tsx:107]: I got it, but what is this header and content are string only, the example I give above ?

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 8 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/Collapsible.tsx:93]: 👍

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 4 above)
Comment (evshi) [reply packages/runtime/src/widgets/Collapsible.tsx:100]: Then that is invalid and an exception will be thrown.

File: apps/kitchen-sink/src/ensemble/screens/home.yaml (hunk 10 above)
[the remark this answers is not in the document]
Comment (evshi) [reply apps/kitchen-sink/src/ensemble/screens/home.yaml:380]: Yes but there is no `CollapsibleItem` in flutter.

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 5 above)
Comment (evshi) [reply packages/runtime/src/widgets/Collapsible.tsx:107]: Strings are also React nodes.

File: apps/kitchen-sink/src/ensemble/screens/home.yaml (hunk 10 above)
[the remark this answers is not in the document]
Comment (sagardspeed2) [reply apps/kitchen-sink/src/ensemble/screens/home.yaml:380]: Yes I know and also we are not using anywhere, I got this example reference from Anser, we are only using properties of `template` from itemTemplate

[the remark this answers is not in the document]
Comment (evshi) [reply apps/kitchen-sink/src/ensemble/screens/home.yaml:380]: Remove this then and put the key back into itemTemplate?

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 11]
```diff
@@ -71,9 +75,63 @@ export type CollapsibleProps = {
...
 
+// Custom hook to evaluate an array of expressions using useEvaluate
+const useEvaluateExpressions = (
+  template: CollapsibleItem,
+  namedData: object[],
+): CollapsibleTemplate[] => {
+  const [evaluatedItems, setEvaluatedItems] = useState<CollapsibleTemplate[]>(
+    [],
+  );
+  const [currentIndex, setCurrentIndex] = useState(-1);
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:86]: Do not do this! Why did you no longer make this a component? This is going to be `n` renders of the entire Collapsible component instead of individual smaller renders.

Change this back to a component. Add a check in the parent Collapsible component so that it doesn't render anything until all the keys have been evaluated.

**Review by evshi — CHANGES_REQUESTED** [review]

File: apps/kitchen-sink/src/ensemble/screens/home.yaml (hunk 10 above)
[the remark this answers is not in the document]
Comment (evshi) [reply apps/kitchen-sink/src/ensemble/screens/home.yaml:380]: Will continue to support this since this is being used in the atlas app.

cc: @sharjeelyunus @anserwaseem

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 12]
```diff
@@ -71,9 +75,79 @@ export type CollapsibleProps = {
...
+    template,
+    currentIndex,
+    setEvaluated,
+  }: {
+    context: object;
+    currentIndex: number;
+    template: CollapsibleItem;
+    setEvaluated: React.Dispatch<React.SetStateAction<CollapsibleTemplate[]>>;
+  }): null => {
+    const evaluatedData = useEvaluate({ ...template }, { context });
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:90]: This should evaluate the key, otherwise you will create additional bindings for label and children attributes you don't need.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 13]
```diff
@@ -71,9 +75,79 @@ export type CollapsibleProps = {
...
+      const content = EnsembleRuntime.render([
+        unwrapWidget(children as string),
+      ]);
+
+      setEvaluated((prev) => {
+        const prevEvaluated = [...prev];
+        prevEvaluated[currentIndex] = { key, label: header, children: content };
+        return prevEvaluated;
+      });
+    }, [currentIndex, evaluatedData, setEvaluated]);
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:108]: This should only check for the key.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 14]
```diff
@@ -71,9 +75,79 @@ export type CollapsibleProps = {
...
+      const header = isString(label)
+        ? label
+        : EnsembleRuntime.render([unwrapWidget(label)]);
+
+      const content = EnsembleRuntime.render([
+        unwrapWidget(children as string),
+      ]);
+
+      setEvaluated((prev) => {
+        const prevEvaluated = [...prev];
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:104]: Why duplicate the array?

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 15]
```diff
@@ -71,9 +75,79 @@ export type CollapsibleProps = {
...
+
+    useEffect(() => {
+      const { key, label, children } = evaluatedData;
+
+      const header = isString(label)
+        ? label
+        : EnsembleRuntime.render([unwrapWidget(label)]);
+
+      const content = EnsembleRuntime.render([
+        unwrapWidget(children as string),
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:100]: The children and label are the same across all the items right? This can be unwrapped once and passed in.

File: packages/runtime/src/widgets/Collapsible.tsx (hunk 14 above)
Comment (sagardspeed2) [reply packages/runtime/src/widgets/Collapsible.tsx:104]: we need a shallow copy because React uses reference equality to detect changes. When you modify the array directly without creating a new reference, React assumes nothing has changed.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 16]
```diff
@@ -71,9 +76,86 @@ export type CollapsibleProps = {
...
+        };
+        return [...prev];
+      });
+    }, [evaluatedData]);
+
+    return null;
+  },
+);
+
+EvaluateItem.displayName = "EvaluateItem";
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:114]: Rename this to be `CollapsibleItem`.

File: packages/runtime/src/widgets/Collapsible.tsx [hunk 17]
```diff
@@ -71,9 +76,86 @@ export type CollapsibleProps = {
...
+
+const withValueTemplate = <P extends object>(
```
Comment (evshi) [inline packages/runtime/src/widgets/Collapsible.tsx:116]: There is no need for this to be a HOC since the logic is not shared anywhere. This is just extra syntax for no value

**Review by evshi — APPROVED** [review]
