### PR TITLE
fix: added tooltip widget

### LINKED ISSUE #875: Implement ToolTip widget
https://studio.ensembleui.com/app/e24402cb-75e2-404c-866c-29e6c3dd7992/screen/zJv4JBOURECx4q0o9lFY

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Added tooltip widget

## Issue ticket number and link

Closes #875 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/widgets/ToolTip.tsx [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  /**
+   * The widget to render as the content of this container.
+   * @treeItemWidgetLabel Set Content Widget
+   */
+  widget: Widget;
+} & EnsembleWidgetProps;
+
+export const ToolTip: React.FC<ToolTipProps> = (props) => {
+  const { widget, onTriggered, ...rest } = props;
+  const unwrappedWidget = unwrapWidget(cloneDeep(widget));
```
Comment (evshi) [inline packages/runtime/src/widgets/ToolTip.tsx:32]: This can be memoized.

**Review by evshi — APPROVED** [review]
