### PR TITLE
fix: added useEffect cleanup in useRegisterBindings

### LINKED ISSUE #861: Cannot call button setLoading multiple times
**Describe the bug**
Put a button in a showDialog with an id and call setLoading. Works first time but not the second time. The issue is the setLoading invokable function becomes stale.

We did a short term fix for forceState but this is no longer needed . We just need to compare function equality.

**To Reproduce**

1. Create a dialog with a button with an ID
2. Call setLoading on the button
3. Close modal
4. Open modal
5. Call setLoading on the button again
6. Button does not enter loading state

**Expected behavior**
Button should enter loading state no matter how many times modal renderes

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
Issue related widget states become stale on component re-render

for example,
added a button on showDialog, opened showDialog and set that button loader to true, close the showDialog and open again, try again to set loader, and this time nothing happen due to setter function become stale.

### Screenshots [Optional]
after:

https://github.com/user-attachments/assets/044425a9-82c9-4c46-a669-b7ea5d25d922

## Issue ticket number and link

Closes #861 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 1]
```diff
@@ -88,6 +88,10 @@ export const useRegisterBindings = <T extends { [key: string]: unknown }>(
     }
   }, [options?.forceState]);
 
+  useEffect(() => {
+    setWidgetState({});
+  }, [setWidgetState]);
```
Comment (sagardspeed2) [inline packages/framework/src/hooks/useRegisterBindings.ts:93]: @evshi this basically reset the values of that widget on widget unmounted. and thus on next render of that element will re-render and again that in `widgetState`

**Comment by evshi** [comment]
@sagardspeed2 this will create infinite renders and cause other dependent expressions to fail. See the failing test. Just update the invokables each time.

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 2]
```diff
@@ -88,6 +88,18 @@ export const useRegisterBindings = <T extends { [key: string]: unknown }>(
...
+    return () => {
+      setWidgetState({
+        values: newValues,
+        invokable: {
+          id: resolvedWidgetId,
+          methods: { ...methods, getId: () => resolvedWidgetId },
+        },
+      });
+    };
+  }, [setWidgetState]);
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:101]: This doesn't seem right. This pushes a state update when the component unmounts, which triggers more renders on dependent widgets. We should limit use of setWidgetState.

Update the comparator on line 61 to better handle functions.

File: packages/runtime/src/widgets/ImageCropper.tsx [hunk 3]
```diff
@@ -38,15 +38,12 @@ export const ImageCropper: React.FC<ImageCropperProps> = (props) => {
...
-      }
-      onCroppedAction.callback({ file });
-    },
-    [onCroppedAction],
-  );
+  const onCroppedActionCallback = useCallback((file: unknown) => {
+    if (!onCroppedAction) {
+      return;
+    }
+    onCroppedAction.callback({ file });
```
Comment (evshi) [inline packages/runtime/src/widgets/ImageCropper.tsx:45]: So this is an example where you do need the action in the dependency, or at the last the callback. If the callback hook changes any of the dependencies this does need to get recomputed.

File: packages/runtime/src/widgets/DataGrid/DataGrid.tsx [hunk 4]
```diff
@@ -215,7 +215,7 @@ export const DataGrid: React.FC<GridProps> = (props) => {
     if (onScrollEndAction) {
       onScrollEndAction.callback();
     }
-  }, [onScrollEndAction]);
+  }, []);
```
Comment (evshi) [inline packages/runtime/src/widgets/DataGrid/DataGrid.tsx:218]: This needs to be at least onScrollEndAction.callback, same for below.

File: packages/runtime/src/widgets/Button.tsx [hunk 5]
```diff
@@ -33,16 +33,13 @@ export type ButtonProps = {
...
-    },
-    [action],
-  );
+  const onClickCallback = useCallback((e?: MouseEvent) => {
+    e?.stopPropagation();
+    if (!action) {
+      return;
+    }
+    action.callback();
+  }, []);
```
Comment (evshi) [inline packages/runtime/src/widgets/Button.tsx:42]: This should be action.callback in the dependency array.

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 6]
```diff
@@ -49,16 +56,23 @@ export const useRegisterBindings = <T extends { [key: string]: unknown }>(
   );
 
   useEffect(() => {
-    // Improves performance greatly: o need to store state in global if there's no explicit ID to reference it with
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:52]: Keep this comment.

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 7]
```diff
@@ -15,6 +15,13 @@ export interface RegisterBindingsResult<T> {
   rootRef: RefCallback<never>;
 }
 
+// eslint-disable-next-line @typescript-eslint/ban-types
+const areFunctionsEqual = (func1?: Function, func2?: Function): boolean => {
+  if (!func1 && !func2) return true;
+  if (!func1 || !func2) return false;
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:21]: Why are these even needed? You can just use triple equal?

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 8]
```diff
@@ -49,16 +56,23 @@ export const useRegisterBindings = <T extends { [key: string]: unknown }>(
...
+      // Check if the method references are equal or if their string representations are the same
+      return areFunctionsEqual(fromMethods, fromWidgets);
+    });
+
     if (
       (options?.comparator
         ? options.comparator(newValues, widgetState?.values)
         : isEqual(newValues, widgetState?.values)) &&
-      isEqual(keys(methods), keys(widgetState?.invokable?.methods))
+      prevStateCheck
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:75]: Combine this function check with the values check.

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 9]
```diff
@@ -70,7 +84,6 @@ export const useRegisterBindings = <T extends { [key: string]: unknown }>(
   }, [
     methods,
     resolvedWidgetId,
-    setWidgetState,
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:73]: Why remove this?

File: packages/runtime/src/widgets/__tests__/Button.test.tsx [hunk 10]
```diff
@@ -228,4 +230,198 @@ test("test button loading using bindings", async () => {
...
+            id="test-button"
+            // eslint-disable-next-line no-template-curly-in-string
+            label="${ensemble.storage.get('btnLabel')}"
+            options={{ debounceMs: 100 }}
+          />
+          <Button
+            label="Change button label"
+            onTap={{
+              executeCode:
+                "ensemble.storage.set('btnLabel', 'Ensemble Button')",
```
Comment (evshi) [inline packages/runtime/src/widgets/__tests__/Button.test.tsx:404]: You need a test that checks the render count when one of the bindings on the actions change.

File: packages/runtime/src/widgets/__tests__/Button.test.tsx [hunk 11]
```diff
@@ -228,4 +230,198 @@ test("test button loading using bindings", async () => {
...
+      );
+    };
+
+    const { getByTestId } = render(<Parent />);
+
+    // Initial render
+    expect(renderCount.current).toBe(1);
+
+    // Update parent state
+    // eslint-disable-next-line @typescript-eslint/require-await
```
Comment (evshi) [inline packages/runtime/src/widgets/__tests__/Button.test.tsx:279]: These shouldn't be needed.

File: packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts [hunk 12]
```diff
@@ -322,3 +338,66 @@ test("evaluates flutter style hex codes expressions", () => {
...
+  // Rerender with the same dependency
+  rerender({ dependency: 1 });
+
+  const secondCallback = result.current;
+
+  // Check that the callback reference remains the same
+  expect(firstCallback.toString()).toBe(secondCallback.toString());
+});
+
+test("should keep the same reference for all functions inside an object when dependencies do not change", () => {
```
[the remark this answers is not in the document]
Comment (evshi) [reply packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts:365]: @sagardspeed2 please add this test.

File: packages/framework/src/hooks/useRegisterBindings.ts (hunk 9 above)
Comment (sagardspeed2) [reply packages/framework/src/hooks/useRegisterBindings.ts:73]: Not needed and not used in that useEffect

File: packages/runtime/src/runtime/hooks/useCloseAllModalScreens.ts [hunk 13]
```diff
@@ -8,7 +8,9 @@ export const useCloseAllScreens: EnsembleActionHook<
 > = () => {
   const { closeAllScreens } = useContext(ModalContext) || {};
 
-  const closeAllModalScreens: () => void = () => closeAllScreens?.();
+  const callback = useCallback(() => {
+    closeAllScreens?.();
+  }, [closeAllScreens]);
 
-  return { callback: closeAllModalScreens };
+  return useMemo(() => ({ callback }), [callback]);
```
Comment (evshi) [inline packages/runtime/src/runtime/hooks/useCloseAllModalScreens.ts:15]: This isn't doing anything

Comment (evshi) [inline packages/runtime/src/runtime/hooks/useCloseAllModalScreens.ts:15]: This isn't doing anything

File: packages/runtime/src/runtime/hooks/useEnsembleAction.tsx [hunk 14]
```diff
@@ -146,7 +146,7 @@ export const useExecuteCode: EnsembleActionHook<
     { modalContext, render: EnsembleRuntime.render, EnsembleScreen },
   );
 
-  return { callback: execute };
+  return useMemo(() => ({ callback: execute }), [execute]);
```
Comment (evshi) [inline packages/runtime/src/runtime/hooks/useEnsembleAction.tsx:149]: Not doing anything.

**Review by evshi — CHANGES_REQUESTED** [review]
Remove all the useMemos where the command is also the dependency that doesn't do anything.

File: packages/framework/src/hooks/useRegisterBindings.ts [hunk 15]
```diff
@@ -15,6 +15,35 @@ export interface RegisterBindingsResult<T> {
   rootRef: RefCallback<never>;
 }
 
+// eslint-disable-next-line @typescript-eslint/ban-types
+const areFunctionsEqual = (func1?: Function, func2?: Function): boolean => {
+  return func1 === func2;
+};
```
Comment (evshi) [inline packages/framework/src/hooks/useRegisterBindings.ts:21]: Can you just inline this so we don't need the linter comment?

File: packages/runtime/src/runtime/hooks/useCloseAllModalScreens.ts [hunk 16]
```diff
@@ -8,7 +8,9 @@ export const useCloseAllScreens: EnsembleActionHook<
 > = () => {
   const { closeAllScreens } = useContext(ModalContext) || {};
 
-  const closeAllModalScreens: () => void = () => closeAllScreens?.();
+  const closeAllModalScreens = useCallback(() => {
+    closeAllScreens?.();
+  }, []);
```
Comment (evshi) [inline packages/runtime/src/runtime/hooks/useCloseAllModalScreens.ts:13]: This should memoize the return object like we discussed.

File: packages/framework/src/hooks/useScreenData.ts [hunk 17]
```diff
@@ -49,11 +51,14 @@ export const useScreenData = (): {
...
   );
 
-  return {
-    apis,
-    sockets,
-    data,
-    setData,
-    mockResponses,
-  };
+  return useMemo(
```
Comment (evshi) [inline packages/framework/src/hooks/useScreenData.ts:54]: Why is this needed again?

Comment (evshi) [reply packages/framework/src/hooks/useScreenData.ts:54]: I think for this hook, unlike the action hooks, since it is used so rarely that we don't need to memoize the return object but fix the usages instead.

File: packages/runtime/src/runtime/hooks/useEnsembleAction.tsx [hunk 18]
```diff
@@ -311,9 +311,9 @@ export const useConnectSocket: EnsembleActionHook<ConnectSocketAction> = (
   }, [
     screenData,
     socket,
-    onSocketConnectAction,
-    onMessageReceiveAction,
-    onSocketDisconnectAction,
+    onSocketConnectAction?.callback,
+    onMessageReceiveAction?.callback,
+    onSocketDisconnectAction?.callback,
```
Comment (evshi) [inline packages/runtime/src/runtime/hooks/useEnsembleAction.tsx:316]: These changes are fine but preferably we need to memoize the action return object.

File: packages/framework/src/hooks/useEvaluate.ts [hunk 19]
```diff
@@ -83,5 +83,7 @@ export const useEvaluate = <T extends Record<string, unknown>>(
     return result;
   }, [updatedValues]);
 
-  return merge({}, updatedValues, hexCodes);
+  return useMemo(() => {
+    return merge({}, updatedValues, hexCodes);
+  }, [updatedValues, hexCodes]);
```
Comment (evshi) [inline packages/framework/src/hooks/useEvaluate.ts:88]: What is the purpose of this?

File: packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (evshi) [reply packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts:367]: @sagardspeed2 you need to add this test.

File: packages/runtime/src/widgets/__tests__/Button.test.tsx (hunk 11 above)
Comment (evshi) [reply packages/runtime/src/widgets/__tests__/Button.test.tsx:280]: @sagardspeed2 please clean this up

File: packages/runtime/src/widgets/__tests__/Button.test.tsx (hunk 10 above)
Comment (evshi) [reply packages/runtime/src/widgets/__tests__/Button.test.tsx:405]: @sagardspeed2 did you add this test somewhere?

**Review by evshi — COMMENTED** [review]
Almost there just a few tests to write to confirm results and clean up

File: packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts [hunk 20]
```diff
@@ -322,3 +341,194 @@ test("evaluates flutter style hex codes expressions", () => {
...
+  );
+
+  // Rerender with new methods
+  rerender({
+    values: testValues,
+    methods: { updateCount: fn2 },
+  });
+
+  await waitFor(() => {
+    const finalScreen = store.get(screenAtom);
```
Comment (evshi) [inline packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts:526]: Can you assert the resulting methods that get returned from `useRegisterBindings` is also updated?

Comment (sagardspeed2) [reply packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts:526]: @evshi we are not getting resulting methods returned from `useRegisterBindings`, we only get `id`, `rootRef` and `values` from `useRegisterBindings`

**Review by evshi — APPROVED** [review]
