### PR TITLE
fix: added cache in API call

### LINKED ISSUE #350: Optimize graphql query state
GraphQL protocol cannot use http cache headers because everything hits the same resource/endpoint. Instead graphQL has its own caching directives, and client can make further caching optimizations.

Use apollo client caching or react-query caching to avoid refetching expensive queries

https://www.apollographql.com/docs/react/caching/overview
https://tanstack.com/query/v4/docs/framework/react/guides/caching

### PR DESCRIPTION
**Pull request by sagardspeed2**
## Describe your changes
fix added cache support in API trigger

## Issue ticket number and link

Closes #350 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] I have added tests
- [x] I have added a changeset `pnpm changeset add`
- [x] I have added example usage in the kitchen sink app

### CODE REVIEW

File: packages/runtime/src/runtime/hooks/useEnsembleAction.tsx [hunk 1]
```diff
@@ -208,32 +210,37 @@ export const useInvokeAPI: EnsembleActionHook<InvokeAPIAction> = (action) => {
...
-              env: appContext?.env,
-              secrets: appContext?.secrets,
-            },
-          },
-          {
-            mockResponse: mockResponse(
-              mockResponses[api.name],
-              useMockResponse,
+        const response = await queryClient.fetchQuery({
+          queryKey: [api.name],
```
Comment (evshi) [inline packages/runtime/src/runtime/hooks/useEnsembleAction.tsx:214]: This needs to be a hash of screen/name/inputs. Otherwise the invoking the same API again on a different screen or different inputs will return the wrong result.

Add a test for this.

File: apps/kitchen-sink/src/ensemble/screens/home.yaml [hunk 2]
```diff
@@ -396,3 +420,9 @@ API:
   ERROR500:
     method: GET
     uri: https://httpstat.us/500
+
+  getDummyProducts:
+    method: GET
+    cache: true
+    cacheTime: 10
```
Comment (evshi) [inline apps/kitchen-sink/src/ensemble/screens/home.yaml:427]: Consolidate to one property called `cacheExpiry`

**Review by evshi — CHANGES_REQUESTED** [review]
You also need to add caching to the other invocation for executeCode.

File: packages/framework/src/api/data.ts [hunk 3]
```diff
@@ -11,6 +12,8 @@ import { screenDataAtom, type ScreenContextDefinition } from "../state";
 import { isUsingMockResponse } from "../appConfig";
 import { mockResponse } from "../evaluate/mock";
 
+const queryClient = new QueryClient();
```
Comment (evshi) [inline packages/framework/src/api/data.ts:15]: You need to use the same instance of the queryClient otherwise it will not be the same cache.

File: packages/framework/src/api/data.ts [hunk 4]
```diff
@@ -23,6 +26,12 @@ export const invokeAPI = async (
     (model) => model.name === apiName,
   );
 
+  const hash = JSON.stringify({
```
Comment (evshi) [inline packages/framework/src/api/data.ts:29]: Make a re-usable function for this that can be shared by framework and runtime.

File: packages/runtime/src/runtime/hooks/__tests__/useActionGroup.test.tsx [hunk 5]
```diff
@@ -164,6 +190,120 @@ test("fetch multiple APIs", async () => {
   });
 });
 
+test("fetch API cache response for cache expiry", async () => {
```
Comment (evshi) [inline packages/runtime/src/runtime/hooks/__tests__/useActionGroup.test.tsx:193]: Move these tests to the useInvokeApi test suite. Also add a test that asserts if the cacheExpiry is not present, then the response is not cached.

File: packages/framework/src/shared/models.ts [hunk 6]
```diff
@@ -70,6 +70,7 @@ export interface EnsembleAPIModel {
   url?: string;
   method: "GET" | "POST" | "PUT" | "PATCH";
   headers?: { [key: string]: string | number | boolean };
+  cacheExpiry?: number;
```
Comment (evshi) [inline packages/framework/src/shared/models.ts:73]: Let's rename this to `cacheExpirySeconds` to make it clear what the unit of measurement is.

**Review by evshi — CHANGES_REQUESTED** [review]

**Review by evshi — APPROVED** [review]
